language: php

php:
  - 5.4
  - 5.5

env:
  - APPLICATION_ENV="testing" DB="mysql" DB_USERNAME="root"

before_install:
  - mysql -u$DB_USERNAME -e 'create database bazalt_cms;'
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('awdawd') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root

before_script:
  - composer self-update
  - composer install --dev --no-interaction
  - composer update
  - mysql -pawdawd -u$DB_USERNAME bazalt_cms < vendor/bazalt/site/install.sql
  - mysql -pawdawd -u$DB_USERNAME bazalt_cms < vendor/bazalt/auth/install.sql
  - mysql -pawdawd -u$DB_USERNAME bazalt_cms < install/components/10-Pages.sql
  - mysql -pawdawd -u$DB_USERNAME bazalt_cms < install/components/20-Users.sql
  - mysql -pawdawd -u$DB_USERNAME bazalt_cms < install/components/40-Payments.sql

script:
  - mkdir -p tmp/logs
  - mkdir -p build/logs
  - phpunit --configuration tests/phpunit.xml.dist

after_script:
  - php vendor/bin/coveralls -v